/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface GeneratedContent {
  'generatedAt' : bigint,
  'mcqCount' : bigint,
  'flashcardCount' : bigint,
  'cheatsheetCount' : bigint,
  'topicId' : bigint,
}
export interface LeaderboardEntry {
  'xp' : bigint,
  'streak' : bigint,
  'username' : string,
  'badges' : Array<string>,
  'rank' : bigint,
  'level' : bigint,
}
export interface Topic {
  'id' : bigint,
  'microTopic' : string,
  'subject' : string,
  'difficulty' : string,
  'description' : string,
  'board' : string,
  'chapter' : string,
  'className' : string,
  'questionCount' : bigint,
}
export interface UserProfile {
  'principal' : string,
  'displayName' : string,
  'createdAt' : bigint,
  'studentClass' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllTopics' : ActorMethod<[], Array<Topic>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getTopicById' : ActorMethod<[bigint], [] | [Topic]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markFlashcardMastered' : ActorMethod<[string, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[string, string], UserProfile>,
  'saveUserProfile' : ActorMethod<[string, string], UserProfile>,
  'simulateAIContentGeneration' : ActorMethod<
    [bigint, string],
    GeneratedContent
  >,
  'submitQuizResult' : ActorMethod<[string, bigint, bigint], [bigint, bigint]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];