/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Topic = IDL.Record({
  'id' : IDL.Nat,
  'microTopic' : IDL.Text,
  'subject' : IDL.Text,
  'difficulty' : IDL.Text,
  'description' : IDL.Text,
  'board' : IDL.Text,
  'chapter' : IDL.Text,
  'className' : IDL.Text,
  'questionCount' : IDL.Nat,
});
export const UserWithRole = IDL.Record({
  'principal' : IDL.Text,
  'displayName' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : IDL.Text,
  'studentClass' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'principal' : IDL.Text,
  'displayName' : IDL.Text,
  'createdAt' : IDL.Int,
  'studentClass' : IDL.Text,
});
export const LeaderboardEntry = IDL.Record({
  'xp' : IDL.Nat,
  'streak' : IDL.Nat,
  'username' : IDL.Text,
  'badges' : IDL.Vec(IDL.Text),
  'rank' : IDL.Nat,
  'level' : IDL.Nat,
});
export const SiteSettings = IDL.Record({
  'lastUpdated' : IDL.Int,
  'announcement' : IDL.Text,
  'updatedBy' : IDL.Text,
  'announcementEnabled' : IDL.Bool,
  'featuredMessage' : IDL.Text,
});
export const GeneratedContent = IDL.Record({
  'generatedAt' : IDL.Int,
  'mcqCount' : IDL.Nat,
  'flashcardCount' : IDL.Nat,
  'cheatsheetCount' : IDL.Nat,
  'topicId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBlogXP' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignOperatorRole' : IDL.Func([IDL.Principal], [], []),
  'checkUsernameAvailability' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'deleteUserProfile' : IDL.Func([IDL.Principal], [], []),
  'dismissOperator' : IDL.Func([IDL.Principal], [], []),
  'getAllOperators' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllTopics' : IDL.Func([], [IDL.Vec(Topic)], ['query']),
  'getAllUsersWithRoles' : IDL.Func([], [IDL.Vec(UserWithRole)], ['query']),
  'getCallerRole' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getSiteSettings' : IDL.Func([], [IDL.Opt(SiteSettings)], ['query']),
  'getTopicById' : IDL.Func([IDL.Nat], [IDL.Opt(Topic)], ['query']),
  'getUserByUsername' : IDL.Func(
      [IDL.Text],
      [
        IDL.Opt(
          IDL.Record({
            'createdAt' : IDL.Int,
            'fullName' : IDL.Text,
            'email' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerOperator' : IDL.Func([], [IDL.Bool], ['query']),
  'login' : IDL.Func(
      [IDL.Text, IDL.Text],
      [
        IDL.Record({
          'ok' : IDL.Bool,
          'fullName' : IDL.Text,
          'email' : IDL.Text,
          'message' : IDL.Text,
        }),
      ],
      [],
    ),
  'markFlashcardMastered' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([IDL.Text, IDL.Text], [UserProfile], []),
  'saveUserProfile' : IDL.Func([IDL.Text, IDL.Text], [UserProfile], []),
  'signUp' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Record({ 'ok' : IDL.Bool, 'message' : IDL.Text })],
      [],
    ),
  'simulateAIContentGeneration' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [GeneratedContent],
      [],
    ),
  'submitQuizResult' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat, IDL.Nat], []),
  'updateSiteSettings' : IDL.Func(
      [IDL.Text, IDL.Bool, IDL.Text],
      [SiteSettings],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Topic = IDL.Record({
    'id' : IDL.Nat,
    'microTopic' : IDL.Text,
    'subject' : IDL.Text,
    'difficulty' : IDL.Text,
    'description' : IDL.Text,
    'board' : IDL.Text,
    'chapter' : IDL.Text,
    'className' : IDL.Text,
    'questionCount' : IDL.Nat,
  });
  const UserWithRole = IDL.Record({
    'principal' : IDL.Text,
    'displayName' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : IDL.Text,
    'studentClass' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'principal' : IDL.Text,
    'displayName' : IDL.Text,
    'createdAt' : IDL.Int,
    'studentClass' : IDL.Text,
  });
  const LeaderboardEntry = IDL.Record({
    'xp' : IDL.Nat,
    'streak' : IDL.Nat,
    'username' : IDL.Text,
    'badges' : IDL.Vec(IDL.Text),
    'rank' : IDL.Nat,
    'level' : IDL.Nat,
  });
  const SiteSettings = IDL.Record({
    'lastUpdated' : IDL.Int,
    'announcement' : IDL.Text,
    'updatedBy' : IDL.Text,
    'announcementEnabled' : IDL.Bool,
    'featuredMessage' : IDL.Text,
  });
  const GeneratedContent = IDL.Record({
    'generatedAt' : IDL.Int,
    'mcqCount' : IDL.Nat,
    'flashcardCount' : IDL.Nat,
    'cheatsheetCount' : IDL.Nat,
    'topicId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBlogXP' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignOperatorRole' : IDL.Func([IDL.Principal], [], []),
    'checkUsernameAvailability' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'deleteUserProfile' : IDL.Func([IDL.Principal], [], []),
    'dismissOperator' : IDL.Func([IDL.Principal], [], []),
    'getAllOperators' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAllTopics' : IDL.Func([], [IDL.Vec(Topic)], ['query']),
    'getAllUsersWithRoles' : IDL.Func([], [IDL.Vec(UserWithRole)], ['query']),
    'getCallerRole' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
    'getSiteSettings' : IDL.Func([], [IDL.Opt(SiteSettings)], ['query']),
    'getTopicById' : IDL.Func([IDL.Nat], [IDL.Opt(Topic)], ['query']),
    'getUserByUsername' : IDL.Func(
        [IDL.Text],
        [
          IDL.Opt(
            IDL.Record({
              'createdAt' : IDL.Int,
              'fullName' : IDL.Text,
              'email' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerOperator' : IDL.Func([], [IDL.Bool], ['query']),
    'login' : IDL.Func(
        [IDL.Text, IDL.Text],
        [
          IDL.Record({
            'ok' : IDL.Bool,
            'fullName' : IDL.Text,
            'email' : IDL.Text,
            'message' : IDL.Text,
          }),
        ],
        [],
      ),
    'markFlashcardMastered' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([IDL.Text, IDL.Text], [UserProfile], []),
    'saveUserProfile' : IDL.Func([IDL.Text, IDL.Text], [UserProfile], []),
    'signUp' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Record({ 'ok' : IDL.Bool, 'message' : IDL.Text })],
        [],
      ),
    'simulateAIContentGeneration' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [GeneratedContent],
        [],
      ),
    'submitQuizResult' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat, IDL.Nat], []),
    'updateSiteSettings' : IDL.Func(
        [IDL.Text, IDL.Bool, IDL.Text],
        [SiteSettings],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };