/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BlogPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'authorUsername' : IDL.Text,
  'content' : IDL.Text,
  'published' : IDL.Bool,
  'createdAt' : IDL.Int,
  'authorName' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
});
export const Topic = IDL.Record({
  'id' : IDL.Nat,
  'microTopic' : IDL.Text,
  'subject' : IDL.Text,
  'difficulty' : IDL.Text,
  'description' : IDL.Text,
  'board' : IDL.Text,
  'chapter' : IDL.Text,
  'className' : IDL.Text,
  'questionCount' : IDL.Nat,
});
export const UserWithRole = IDL.Record({
  'principal' : IDL.Text,
  'displayName' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : IDL.Text,
  'studentClass' : IDL.Text,
});
export const LeaderboardEntry = IDL.Record({
  'xp' : IDL.Nat,
  'streak' : IDL.Nat,
  'username' : IDL.Text,
  'badges' : IDL.Vec(IDL.Text),
  'rank' : IDL.Nat,
  'level' : IDL.Nat,
});
export const SiteSettings = IDL.Record({
  'lastUpdated' : IDL.Int,
  'announcement' : IDL.Text,
  'updatedBy' : IDL.Text,
  'announcementEnabled' : IDL.Bool,
  'featuredMessage' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'principal' : IDL.Text,
  'displayName' : IDL.Text,
  'createdAt' : IDL.Int,
  'studentClass' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBlogXP' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkUsernameAvailability' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'createBlogPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteBlogPost' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'deleteUserProfile' : IDL.Func([IDL.Principal], [], []),
  'getAdminStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalXP' : IDL.Nat,
          'totalAdmins' : IDL.Nat,
          'totalOperators' : IDL.Nat,
          'totalUsers' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getAllAdmins' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getAllBlogPostsAdmin' : IDL.Func([IDL.Text], [IDL.Vec(BlogPost)], ['query']),
  'getAllBlogPostsByAuthor' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(BlogPost)],
      ['query'],
    ),
  'getAllBlogPostsPublic' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getAllBlogPostsPublicAdmin' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getAllOperators' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllRoles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Record({ 'username' : IDL.Text, 'role' : IDL.Text }))],
      ['query'],
    ),
  'getAllTopics' : IDL.Func([], [IDL.Vec(Topic)], ['query']),
  'getAllUsersWithPrincipalRoles' : IDL.Func(
      [],
      [IDL.Vec(UserWithRole)],
      ['query'],
    ),
  'getAllUsersWithRoles' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'username' : IDL.Text,
            'createdAt' : IDL.Int,
            'role' : IDL.Text,
            'fullName' : IDL.Text,
            'email' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
  'getAllUsersWithRolesPublic' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'username' : IDL.Text,
            'createdAt' : IDL.Int,
            'role' : IDL.Text,
            'fullName' : IDL.Text,
            'email' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
  'getBlogPostById' : IDL.Func([IDL.Nat], [IDL.Opt(BlogPost)], ['query']),
  'getBlogPostImageById' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Text)], ['query']),
  'getCallerRole' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getRoleCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getRoleDetails' : IDL.Func(
      [IDL.Text],
      [
        IDL.Opt(
          IDL.Record({
            'username' : IDL.Text,
            'createdAt' : IDL.Int,
            'role' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
  'getRoleSummary' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalAdmins' : IDL.Nat,
          'totalOperators' : IDL.Nat,
          'totalUsers' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getSiteSettings' : IDL.Func([], [IDL.Opt(SiteSettings)], ['query']),
  'getTopicById' : IDL.Func([IDL.Nat], [IDL.Opt(Topic)], ['query']),
  'getTotalRoles' : IDL.Func(
      [],
      [IDL.Record({ 'operators' : IDL.Nat, 'admins' : IDL.Nat })],
      ['query'],
    ),
  'getUserByUsername' : IDL.Func(
      [IDL.Text],
      [
        IDL.Opt(
          IDL.Record({
            'createdAt' : IDL.Int,
            'fullName' : IDL.Text,
            'email' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserRole' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getUsernameRole' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'hasRole' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isOperatorRole' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isStrictAdmin' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'login' : IDL.Func(
      [IDL.Text, IDL.Text],
      [
        IDL.Record({
          'ok' : IDL.Bool,
          'fullName' : IDL.Text,
          'email' : IDL.Text,
          'message' : IDL.Text,
        }),
      ],
      [],
    ),
  'markFlashcardMastered' : IDL.Func([IDL.Nat], [], []),
  'publishBlogPost' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'reassignUsernameRole' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'removeUsernameRole' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([IDL.Text, IDL.Text], [UserProfile], []),
  'searchBlogPosts' : IDL.Func([IDL.Text], [IDL.Vec(BlogPost)], ['query']),
  'setUsernameRole' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
  'signUp' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Record({ 'ok' : IDL.Bool, 'message' : IDL.Text })],
      [],
    ),
  'unpublishBlogPost' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateBlogPost' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Text],
      [],
      [],
    ),
  'updateSiteSettings' : IDL.Func(
      [IDL.Text, IDL.Bool, IDL.Text],
      [SiteSettings],
      [],
    ),
  'updateUserProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Record({ 'ok' : IDL.Bool, 'message' : IDL.Text })],
      [],
    ),
  'validateRoleAssignment' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BlogPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'authorUsername' : IDL.Text,
    'content' : IDL.Text,
    'published' : IDL.Bool,
    'createdAt' : IDL.Int,
    'authorName' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
  });
  const Topic = IDL.Record({
    'id' : IDL.Nat,
    'microTopic' : IDL.Text,
    'subject' : IDL.Text,
    'difficulty' : IDL.Text,
    'description' : IDL.Text,
    'board' : IDL.Text,
    'chapter' : IDL.Text,
    'className' : IDL.Text,
    'questionCount' : IDL.Nat,
  });
  const UserWithRole = IDL.Record({
    'principal' : IDL.Text,
    'displayName' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : IDL.Text,
    'studentClass' : IDL.Text,
  });
  const LeaderboardEntry = IDL.Record({
    'xp' : IDL.Nat,
    'streak' : IDL.Nat,
    'username' : IDL.Text,
    'badges' : IDL.Vec(IDL.Text),
    'rank' : IDL.Nat,
    'level' : IDL.Nat,
  });
  const SiteSettings = IDL.Record({
    'lastUpdated' : IDL.Int,
    'announcement' : IDL.Text,
    'updatedBy' : IDL.Text,
    'announcementEnabled' : IDL.Bool,
    'featuredMessage' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'principal' : IDL.Text,
    'displayName' : IDL.Text,
    'createdAt' : IDL.Int,
    'studentClass' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBlogXP' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkUsernameAvailability' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'createBlogPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteBlogPost' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'deleteUserProfile' : IDL.Func([IDL.Principal], [], []),
    'getAdminStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalXP' : IDL.Nat,
            'totalAdmins' : IDL.Nat,
            'totalOperators' : IDL.Nat,
            'totalUsers' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getAllAdmins' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getAllBlogPostsAdmin' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BlogPost)],
        ['query'],
      ),
    'getAllBlogPostsByAuthor' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BlogPost)],
        ['query'],
      ),
    'getAllBlogPostsPublic' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getAllBlogPostsPublicAdmin' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getAllOperators' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAllRoles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Record({ 'username' : IDL.Text, 'role' : IDL.Text }))],
        ['query'],
      ),
    'getAllTopics' : IDL.Func([], [IDL.Vec(Topic)], ['query']),
    'getAllUsersWithPrincipalRoles' : IDL.Func(
        [],
        [IDL.Vec(UserWithRole)],
        ['query'],
      ),
    'getAllUsersWithRoles' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'username' : IDL.Text,
              'createdAt' : IDL.Int,
              'role' : IDL.Text,
              'fullName' : IDL.Text,
              'email' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
    'getAllUsersWithRolesPublic' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'username' : IDL.Text,
              'createdAt' : IDL.Int,
              'role' : IDL.Text,
              'fullName' : IDL.Text,
              'email' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
    'getBlogPostById' : IDL.Func([IDL.Nat], [IDL.Opt(BlogPost)], ['query']),
    'getBlogPostImageById' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getCallerRole' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
    'getRoleCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getRoleDetails' : IDL.Func(
        [IDL.Text],
        [
          IDL.Opt(
            IDL.Record({
              'username' : IDL.Text,
              'createdAt' : IDL.Int,
              'role' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
    'getRoleSummary' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalAdmins' : IDL.Nat,
            'totalOperators' : IDL.Nat,
            'totalUsers' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getSiteSettings' : IDL.Func([], [IDL.Opt(SiteSettings)], ['query']),
    'getTopicById' : IDL.Func([IDL.Nat], [IDL.Opt(Topic)], ['query']),
    'getTotalRoles' : IDL.Func(
        [],
        [IDL.Record({ 'operators' : IDL.Nat, 'admins' : IDL.Nat })],
        ['query'],
      ),
    'getUserByUsername' : IDL.Func(
        [IDL.Text],
        [
          IDL.Opt(
            IDL.Record({
              'createdAt' : IDL.Int,
              'fullName' : IDL.Text,
              'email' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserRole' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getUsernameRole' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'hasRole' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isOperatorRole' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'isStrictAdmin' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'login' : IDL.Func(
        [IDL.Text, IDL.Text],
        [
          IDL.Record({
            'ok' : IDL.Bool,
            'fullName' : IDL.Text,
            'email' : IDL.Text,
            'message' : IDL.Text,
          }),
        ],
        [],
      ),
    'markFlashcardMastered' : IDL.Func([IDL.Nat], [], []),
    'publishBlogPost' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'reassignUsernameRole' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'removeUsernameRole' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([IDL.Text, IDL.Text], [UserProfile], []),
    'searchBlogPosts' : IDL.Func([IDL.Text], [IDL.Vec(BlogPost)], ['query']),
    'setUsernameRole' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'signUp' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Record({ 'ok' : IDL.Bool, 'message' : IDL.Text })],
        [],
      ),
    'unpublishBlogPost' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateBlogPost' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Text],
        [],
        [],
      ),
    'updateSiteSettings' : IDL.Func(
        [IDL.Text, IDL.Bool, IDL.Text],
        [SiteSettings],
        [],
      ),
    'updateUserProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Record({ 'ok' : IDL.Bool, 'message' : IDL.Text })],
        [],
      ),
    'validateRoleAssignment' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };