/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface GeneratedContent {
  'generatedAt' : bigint,
  'mcqCount' : bigint,
  'flashcardCount' : bigint,
  'cheatsheetCount' : bigint,
  'topicId' : bigint,
}
export interface LeaderboardEntry {
  'xp' : bigint,
  'streak' : bigint,
  'username' : string,
  'badges' : Array<string>,
  'rank' : bigint,
  'level' : bigint,
}
export interface SiteSettings {
  'lastUpdated' : bigint,
  'announcement' : string,
  'updatedBy' : string,
  'announcementEnabled' : boolean,
  'featuredMessage' : string,
}
export interface Topic {
  'id' : bigint,
  'microTopic' : string,
  'subject' : string,
  'difficulty' : string,
  'description' : string,
  'board' : string,
  'chapter' : string,
  'className' : string,
  'questionCount' : bigint,
}
export interface UserProfile {
  'principal' : string,
  'displayName' : string,
  'createdAt' : bigint,
  'studentClass' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserWithRole {
  'principal' : string,
  'displayName' : string,
  'createdAt' : bigint,
  'role' : string,
  'studentClass' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBlogXP' : ActorMethod<[bigint], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignOperatorRole' : ActorMethod<[Principal], undefined>,
  'checkUsernameAvailability' : ActorMethod<[string], boolean>,
  'deleteUserProfile' : ActorMethod<[Principal], undefined>,
  'dismissOperator' : ActorMethod<[Principal], undefined>,
  'getAllOperators' : ActorMethod<[], Array<string>>,
  'getAllTopics' : ActorMethod<[], Array<Topic>>,
  'getAllUsersWithRoles' : ActorMethod<[], Array<UserWithRole>>,
  'getCallerRole' : ActorMethod<[], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getSiteSettings' : ActorMethod<[], [] | [SiteSettings]>,
  'getTopicById' : ActorMethod<[bigint], [] | [Topic]>,
  'getUserByUsername' : ActorMethod<
    [string],
    [] | [{ 'createdAt' : bigint, 'fullName' : string, 'email' : string }]
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerOperator' : ActorMethod<[], boolean>,
  'login' : ActorMethod<
    [string, string],
    {
      'ok' : boolean,
      'fullName' : string,
      'email' : string,
      'message' : string,
    }
  >,
  'markFlashcardMastered' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[string, string], UserProfile>,
  'saveUserProfile' : ActorMethod<[string, string], UserProfile>,
  'signUp' : ActorMethod<
    [string, string, string, string],
    { 'ok' : boolean, 'message' : string }
  >,
  'simulateAIContentGeneration' : ActorMethod<
    [bigint, string],
    GeneratedContent
  >,
  'submitQuizResult' : ActorMethod<[bigint, bigint], [bigint, bigint]>,
  'updateSiteSettings' : ActorMethod<[string, boolean, string], SiteSettings>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];