/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Topic = IDL.Record({
  'id' : IDL.Nat,
  'microTopic' : IDL.Text,
  'subject' : IDL.Text,
  'difficulty' : IDL.Text,
  'description' : IDL.Text,
  'board' : IDL.Text,
  'chapter' : IDL.Text,
  'className' : IDL.Text,
  'questionCount' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'principal' : IDL.Text,
  'displayName' : IDL.Text,
  'createdAt' : IDL.Int,
  'studentClass' : IDL.Text,
});
export const LeaderboardEntry = IDL.Record({
  'xp' : IDL.Nat,
  'streak' : IDL.Nat,
  'username' : IDL.Text,
  'badges' : IDL.Vec(IDL.Text),
  'rank' : IDL.Nat,
  'level' : IDL.Nat,
});
export const GeneratedContent = IDL.Record({
  'generatedAt' : IDL.Int,
  'mcqCount' : IDL.Nat,
  'flashcardCount' : IDL.Nat,
  'cheatsheetCount' : IDL.Nat,
  'topicId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllTopics' : IDL.Func([], [IDL.Vec(Topic)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getTopicById' : IDL.Func([IDL.Nat], [IDL.Opt(Topic)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markFlashcardMastered' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([IDL.Text, IDL.Text], [UserProfile], []),
  'saveUserProfile' : IDL.Func([IDL.Text, IDL.Text], [UserProfile], []),
  'simulateAIContentGeneration' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [GeneratedContent],
      [],
    ),
  'submitQuizResult' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Nat, IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Topic = IDL.Record({
    'id' : IDL.Nat,
    'microTopic' : IDL.Text,
    'subject' : IDL.Text,
    'difficulty' : IDL.Text,
    'description' : IDL.Text,
    'board' : IDL.Text,
    'chapter' : IDL.Text,
    'className' : IDL.Text,
    'questionCount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'principal' : IDL.Text,
    'displayName' : IDL.Text,
    'createdAt' : IDL.Int,
    'studentClass' : IDL.Text,
  });
  const LeaderboardEntry = IDL.Record({
    'xp' : IDL.Nat,
    'streak' : IDL.Nat,
    'username' : IDL.Text,
    'badges' : IDL.Vec(IDL.Text),
    'rank' : IDL.Nat,
    'level' : IDL.Nat,
  });
  const GeneratedContent = IDL.Record({
    'generatedAt' : IDL.Int,
    'mcqCount' : IDL.Nat,
    'flashcardCount' : IDL.Nat,
    'cheatsheetCount' : IDL.Nat,
    'topicId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllTopics' : IDL.Func([], [IDL.Vec(Topic)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
    'getTopicById' : IDL.Func([IDL.Nat], [IDL.Opt(Topic)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markFlashcardMastered' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([IDL.Text, IDL.Text], [UserProfile], []),
    'saveUserProfile' : IDL.Func([IDL.Text, IDL.Text], [UserProfile], []),
    'simulateAIContentGeneration' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [GeneratedContent],
        [],
      ),
    'submitQuizResult' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Nat, IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };