/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'id' : bigint,
  'title' : string,
  'authorUsername' : string,
  'content' : string,
  'published' : boolean,
  'createdAt' : bigint,
  'authorName' : string,
  'description' : string,
  'imageUrl' : string,
}
export interface LeaderboardEntry {
  'xp' : bigint,
  'streak' : bigint,
  'username' : string,
  'badges' : Array<string>,
  'rank' : bigint,
  'level' : bigint,
}
export interface SiteSettings {
  'lastUpdated' : bigint,
  'announcement' : string,
  'updatedBy' : string,
  'announcementEnabled' : boolean,
  'featuredMessage' : string,
}
export interface Topic {
  'id' : bigint,
  'microTopic' : string,
  'subject' : string,
  'difficulty' : string,
  'description' : string,
  'board' : string,
  'chapter' : string,
  'className' : string,
  'questionCount' : bigint,
}
export interface UserProfile {
  'principal' : string,
  'displayName' : string,
  'createdAt' : bigint,
  'studentClass' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserWithRole {
  'principal' : string,
  'displayName' : string,
  'createdAt' : bigint,
  'role' : string,
  'studentClass' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBlogXP' : ActorMethod<[bigint], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkUsernameAvailability' : ActorMethod<[string], boolean>,
  'createBlogPost' : ActorMethod<
    [string, string, string, string, string, string],
    bigint
  >,
  'deleteBlogPost' : ActorMethod<[bigint, string], undefined>,
  'deleteUserProfile' : ActorMethod<[Principal], undefined>,
  'getAdminStats' : ActorMethod<
    [],
    {
      'totalXP' : bigint,
      'totalAdmins' : bigint,
      'totalOperators' : bigint,
      'totalUsers' : bigint,
    }
  >,
  'getAllAdmins' : ActorMethod<[], Array<string>>,
  'getAllBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getAllBlogPostsAdmin' : ActorMethod<[string], Array<BlogPost>>,
  'getAllBlogPostsByAuthor' : ActorMethod<[string], Array<BlogPost>>,
  'getAllBlogPostsPublic' : ActorMethod<[], Array<BlogPost>>,
  'getAllBlogPostsPublicAdmin' : ActorMethod<[], Array<BlogPost>>,
  'getAllOperators' : ActorMethod<[], Array<string>>,
  'getAllRoles' : ActorMethod<
    [],
    Array<{ 'username' : string, 'role' : string }>
  >,
  'getAllTopics' : ActorMethod<[], Array<Topic>>,
  'getAllUsersWithPrincipalRoles' : ActorMethod<[], Array<UserWithRole>>,
  'getAllUsersWithRoles' : ActorMethod<
    [],
    Array<
      {
        'username' : string,
        'createdAt' : bigint,
        'role' : string,
        'fullName' : string,
        'email' : string,
      }
    >
  >,
  'getAllUsersWithRolesPublic' : ActorMethod<
    [],
    Array<
      {
        'username' : string,
        'createdAt' : bigint,
        'role' : string,
        'fullName' : string,
        'email' : string,
      }
    >
  >,
  'getBlogPostById' : ActorMethod<[bigint], [] | [BlogPost]>,
  'getBlogPostImageById' : ActorMethod<[bigint], [] | [string]>,
  'getCallerRole' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getRoleCount' : ActorMethod<[string], bigint>,
  'getRoleDetails' : ActorMethod<
    [string],
    [] | [{ 'username' : string, 'createdAt' : bigint, 'role' : string }]
  >,
  'getRoleSummary' : ActorMethod<
    [],
    { 'totalAdmins' : bigint, 'totalOperators' : bigint, 'totalUsers' : bigint }
  >,
  'getSiteSettings' : ActorMethod<[], [] | [SiteSettings]>,
  'getTopicById' : ActorMethod<[bigint], [] | [Topic]>,
  'getTotalRoles' : ActorMethod<
    [],
    { 'operators' : bigint, 'admins' : bigint }
  >,
  'getUserByUsername' : ActorMethod<
    [string],
    [] | [{ 'createdAt' : bigint, 'fullName' : string, 'email' : string }]
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserRole' : ActorMethod<[string], string>,
  'getUsernameRole' : ActorMethod<[string], string>,
  'hasRole' : ActorMethod<[string, string], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isOperatorRole' : ActorMethod<[string], boolean>,
  'isStrictAdmin' : ActorMethod<[string], boolean>,
  'login' : ActorMethod<
    [string, string],
    {
      'ok' : boolean,
      'fullName' : string,
      'email' : string,
      'message' : string,
    }
  >,
  'markFlashcardMastered' : ActorMethod<[bigint], undefined>,
  'publishBlogPost' : ActorMethod<[bigint, string], undefined>,
  'reassignUsernameRole' : ActorMethod<[string, string, string], boolean>,
  'removeUsernameRole' : ActorMethod<[string, string], boolean>,
  'saveCallerUserProfile' : ActorMethod<[string, string], UserProfile>,
  'searchBlogPosts' : ActorMethod<[string], Array<BlogPost>>,
  'setUsernameRole' : ActorMethod<[string, string, string], boolean>,
  'signUp' : ActorMethod<
    [string, string, string, string],
    { 'ok' : boolean, 'message' : string }
  >,
  'unpublishBlogPost' : ActorMethod<[bigint, string], undefined>,
  'updateBlogPost' : ActorMethod<
    [bigint, string, string, string, string, boolean, string],
    undefined
  >,
  'updateSiteSettings' : ActorMethod<[string, boolean, string], SiteSettings>,
  'updateUserProfile' : ActorMethod<
    [string, string, string],
    { 'ok' : boolean, 'message' : string }
  >,
  'validateRoleAssignment' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];